name: 'Get & Cache Dependencies'
description: 'Ger the dependencies and cache them'
inputs:
  caching:
      description: "Whether to cache dependencies or not"
      required: false
      default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-deps-${{ hashFiles('**composer.lock')}}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: composer install
      shell: bash