name: 'Get & Cache Dependencies'
description: 'Ger the dependencies and cache them'
runs:
    using: 'composite'
    steps:
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: npm-deps-${{ hashFiles('**composer.lock')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install
        shell: bash