name: Matrix demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix: 
        php-version: [7.4, 8.0, 8.1]
        operation-system: [ubuntu-latest, windows-latest]
        include:
          - php-version: [ubuntu-latest]
            operation-system: 7.3
        exclude:
          - php-version: 8.2
            operation-system: windows-latest
    runs-on: ${{ matrix.operation-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install dependencies
        run: echo "installing dummy...."
      - name: Build project
        run: echo "build dummy...."